---
- get_url: url={{nite2_src_url}} dest={{nite2_src_zip}}

- unarchive: src={{nite2_src_zip}} dest={{tmp_dir}}
- unarchive: src={{nite2_src_bz2}} dest={{tmp_dir}}

- copy: src='{{nite2_src_dir}}/Include/' dest=/usr/local/include
  sudo: yes

- copy: src='{{nite2_src_dir}}/Redist/' dest=/usr/local/lib
  sudo: yes
