---
- hosts: localhost
  vars:
    - tmp_dir: /tmp
    - install_prefix: /usr/local
    - make_jobs: "{{ansible_processor_count * ansible_processor_cores}}"

  roles:
  - pcl
  - qt5
  - nite2

  tasks:
  - name: Install dependencies
    sudo: yes
    apt: pkg={{item}}  update_cache=yes
    with_items:
    - libboost-program-options-dev
    - libvtk6-qt-dev
    - libyaml-cpp-dev
