---
- get_url: url={{qt5_src_url}} dest={{qt5_src_file}}

- unarchive: src={{qt5_src_file}} dest={{tmp_dir}}

- command: ./configure -prefix {{install_prefix}} -opensource -qt-xcb -confirm-license
  args:
    chdir: "{{qt5_src_dir}}"

- command: make -j{{make_jobs}}
  args:
    chdir: "{{qt5_src_dir}}"

- command: make install
  sudo: yes
  args:
    chdir: "{{qt5_src_dir}}"
